FROM maven:3.8.7-eclipse-temurin-8-alpine as build
WORKDIR /mavenwebapp
COPY . . 
RUN mvn clean package

FROM tomcat:9.0.71-jdk8-temurin-jammy
COPY --from=build /mavenwebapp/target/maven-web-application.war /usr/local/tomcat/webapps/maven-web-application.war